# Generated by Django 5.2.7 on 2025-10-11 11:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_randommodel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MixinPaymentFaceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_json', models.JSONField(null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=50)),
                ('payment_gateway', models.CharField(blank=True, help_text='نام درگاه پرداخت (مثل Zarinpal، IDPay، یا ...) ', max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='شناسه تراکنش از سمت درگاه', max_length=255, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ پرداخت شده', max_digits=12, null=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='زمان انجام پرداخت', null=True)),
                ('server_id_process', models.GenericIPAddressField()),
                ('jwt_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
